FROM registry.fedoraproject.org/fedora:40

LABEL org.opencontainers.image.description="Simple container image just for create RPM and APT repo."

# deb-reversion is in devscripts

RUN dnf -y install createrepo_c reprepro dpkg devscripts jq wget tree rpm-sign gnupg git \
    rpm-build binutils policycoreutils policycoreutils-python-utils selinux-policy-devel \
    --setopt=install_weak_deps=False \
    --setopt=keepcache=True &&\
    dnf -y install ruby rubygem-json \
    --setopt=keepcache=True \
    --exclude=rubygem-rdoc &&\
    rm -rf /var/log/dnf.log

    # From the line of the rpm-build is the requirements of the SELinux config rpm builder 

RUN gem update --system --no-document &&\
    gem install fpm --no-document &&\
    gem clean
