name: Build and Push Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 3 * *'  # Runs on the 3rd of every month at 00:30 UTC
  pull_request:
    branches:
      - '**'  # Triggers on PRs to any branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set date tag
        run: echo "DATE_TAG=$(date '+%Y%m%d')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine if push is needed
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.user.login }}" == "renovate[bot]" ]]; then
            echo "PUSH_IMAGE=false" >> $GITHUB_ENV
          else
            echo "PUSH_IMAGE=true" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ env.PUSH_IMAGE }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.DATE_TAG }}
            ghcr.io/${{ github.repository }}:latest
