name: Cleanup Old Images
on:
  schedule:
    - cron: "15 1 * * 4" # Runs at 01:15, only on Thursday. 
  workflow_dispatch:

jobs:
  delete-older-than-30:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit
      - name: Delete Images Older Than 30 Days
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: fedora-createrepo-image
          older-than: 30 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7
