name: Cleanup Old Images
on:
  schedule:
    - cron: "15 1 * * 4" # Runs at 01:15, only on Thursday. 
  workflow_dispatch:

jobs:
  delete-older-than-30:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit
      - name: Delete Images Older Than 30 Days
        uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: fedora-createrepo-image
          older-than: 30 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7
