name: Build minimal imege
on:
  workflow_dispatch:
  schedule:
    # Every Saturday at 2AM UTC
    - cron: "0 2 * * 6"

permissions:
  contents: read
  packages: write
  id-token: write # needed for signing the images with GitHub OIDC Token

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    with:
      image_name: ${{ github.repository }}-minimal
      path: minimal
      push_to_ghcr: true